### ISSUE TITLE
Add in Events

### ISSUE THREAD

**Issue by vincentdavis** [we-race-here/wrh-brac#13]
Seem that you already have the events because you select the events in the race results.
Let's list and provide a event search and maybe we will import the event files/PDFs later.

<img width="305" alt="Screenshot 2022-12-04 at 6 00 54 PM" src="https://user-images.githubusercontent.com/232564/205527624-77e836fc-c3e5-455d-a338-1ea8a083f3b2.png">

**Comment by karthicksakkaravarti** [comment]
On Hold
