### ISSUE TITLE
Updates to home page

### ISSUE THREAD

**Issue by vincentdavis** [we-race-here/wrh-brac#15]
- Add admin setting to change the Banner images on home page
- Remove event /calendar
- Remove sponsors on bottom
- Where the Calendar/events is, add a formatted text field with the ability to edit the text in the admin.

<img width="1322" alt="Screenshot 2022-12-04 at 6 14 31 PM" src="https://user-images.githubusercontent.com/232564/205528695-1c8e2008-0a0a-43d9-afe3-7609a6d958c0.png">

<img width="1346" alt="Screenshot 2022-12-04 at 6 16 30 PM" src="https://user-images.githubusercontent.com/232564/205528767-00872a01-be65-4ffc-be43-e25086606dd7.png">

**Comment by karthicksakkaravarti** [comment]
Home Banner Image: 
https://archive.coloradocycling.org/BRAC/admin/app/homebannerimage/

**Comment by karthicksakkaravarti** [comment]
Home Information: 
https://archive.coloradocycling.org/BRAC/admin/app/homeinformation/
