### ISSUE TITLE
Result menu

### ISSUE THREAD

**Issue by vincentdavis** [we-race-here/wrh-brac#17]
The Result menu drop-down does not work well on mobile.
Lets split into nicer looking button across the top of the banner image.

**Road:**
- Road
- Road Cup
- Road Cup Team

**Cross:**
- Cross
- Cross Cup
- Cross Team Cup

**Track:**
- Track Omnium

**MTB**
- MTB

**Rider search**
- Search

**Comment by karthicksakkaravarti** [comment]
Added Mobile look view. not changed
